version: "3"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: npm start
        environment: 
            - COOKIE_SECRET=HWdS9%Oz4MSn^FevmhXg3&k&p1ykE
        volumes:
            - ./backend:/usr/src/app/backend
            - logvolume0:/var/log
        links:
            - redis
        ports:
            - "3001:3001"
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        command: npm run dev
        environment:
            - BACKEND_URL=http://localhost:3001
        volumes:
            - ./frontend:/usr/src/app/frontend
        depends_on:
            - backend
        links:
            - redis
        ports:
            - "3000:3000"
    redis:
        image: "redis:alpine"
        logging:
            driver: "none"
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data/postgres
        logging:
            driver: "none"
        ports:
            - '5438:5432'
        volumes:
            - postgres:/data/postgres
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        logging:
            driver: "none"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
volumes:
    logvolume0: {}
    postgres:
