version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
            - logvolume0:/var/log
        links:
            - redis
        ports:
            - "3000:3000"
    redis:
        image: "redis:alpine"
volumes:
    logvolume0: {}