version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/usr/src/app/src
            - logvolume0:/var/log
        links:
            - redis
        ports:
            - "3000:3000"
    redis:
        image: "redis:alpine"
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data/postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - '5438:5432'
        volumes:
            - postgres:/data/postgres
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
volumes:
    logvolume0: {}
    postgres: